### ISSUE TITLE
Element.prototype.matches undefined in IE10/IE11

### ISSUE THREAD

**Issue by david-camdzic** [matsko/ng4-animations-preview#1]
Since matches is not available on Element (in the TransitionAnimationEngine: \node_modules\@angular\animations\@angular\animations\browser.js:4038), I had to add a polyfill for matches into polyfills.ts (copied from MDN) to work with IE11:

if (!Element.prototype.matches) {
	Element.prototype.matches =
		(<any>Element.prototype).matchesSelector ||
		(<any>Element.prototype).mozMatchesSelector ||
		(<any>Element.prototype).msMatchesSelector ||
		(<any>Element.prototype).oMatchesSelector ||
		(<any>Element.prototype).webkitMatchesSelector ||
		function (s) {
			var matches = (this.document || this.ownerDocument).querySelectorAll(s),
				i = matches.length;
			while (--i >= 0 && matches.item(i) !== this) { }
			return i > -1;
		};
}

**Comment by matsko** [comment]
This looks like it needs to be `Element.prototype.msMatchesSelector`. Thank you for the heads up.

**Comment by matsko** [comment]
This is fixed in Angular master.
