### ISSUE TITLE
safari

### ISSUE THREAD

**Issue by fxck** [matsko/ng4-animations-preview#2]
Have you tried running it in safari? Is it buggy simply because you didn't optimize it, or is it because of some buggy polyfill or something?

cc @matsko

**Comment by matsko** [comment]
Yes it's flickery, but for internal reasons. The fixes are going into the engine.

**Comment by fxck** [comment]
Alright, any particular issues I can follow in the main repo, @matsko ?

**Comment by matsko** [comment]
Try it now in Safari: http://slides.yearofmoo.com/ng4-animations-preview/demo/
