### ISSUE TITLE
ng 4.1.0

### ISSUE THREAD

**Issue by maku** [matsko/ng4-animations-preview#3]
Should this example app work with angular 4.1.0?

I tried this and got a bunch of errors: 

e.g.
```
/@angular/animations/animations"' has no exported member 'wait'
```

**Comment by maisnamraju** [comment]
It works only only on the animation-preview branch as far as I know?

**Comment by matsko** [comment]
FYI, it's apart of `4.2.0-rc2` and it will be fully documented in the `4.2.` final release.

The package.json deps in this project have been updated. Sorry for the wait.
