### ISSUE TITLE
Route animation in lazy loaded modules

### ISSUE THREAD

**Issue by GoodGame** [matsko/ng4-animations-preview#4]
How can I enable animation in lazy loaded modules?

If I add 'BrowserAnimationsModule' only into my app.module.ts, I get: 
`Error: Found the synthetic property @pageAnimation. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application`

If I add 'BrowserAnimationsModule' both into app.module.ts and lazy-loaded.module.td, I get:
`Error: BrowserModule has already been loaded`

**Comment by infinite2009** [comment]
I have the same puzzle like you
